### PR TITLE
Fixed  multiple setState calls on text prop / added fontFamily change Text entity

### LINKED ISSUE #25: Repeteadly calls setState when adding a prop text
Hello, just moved from terrylinla to this fork, I'm using the canvas to develop a sticker maker tool and I realized that if you try to add text to the canvas it repeteadly changes the state and ends up crashing.

That's due to: (Lines 146 to 153)

```
 componentDidUpdate(prevProps, prevState) {
       if (prevState.text !== this.state.text) {
       this.setState({
       text: this.state.text,
       });
     }
  }
```

text prop expects an array of objects like that:

`text={[
                      {
                        text: 'sample',
                        font: 'SAF',
                        fontSize: 24,
                        fontColor: 'red',
                        overlay: 'TextOnSketch',
                        anchor: {x: 0, y: 1},
                        position: {x: 100, y: 200},
                        coordinate: 'Absolute',
                        alignment: 'Center',
                        lineHeightMultiple: 1.2,
                      },
                    ]}`

So the array !== array will always change the state and crash.

Sorry for my broken english and thanks a lot for improving the library since owner stopped updating it. I'd also like to know if there's a way to rotate the text added to the canvas. 

Have a nice day.

### PR DESCRIPTION
**Pull request by QuevedoIB**
Removed the ComponentDidUpdate  
Fixes #25 

Added fontFamily change for text entities: 

canvasRef.changeSelectedShapeFont("fontFamilyName");

### CODE REVIEW

**Comment by creambyemute** [comment]
@QuevedoIB I can't accept this PR as it changes things that are not needed for what I think you want to achieve. 
You've changed MotionEntity to TextEntity and the shape selection changed, was this really your intent?

Also the array of text you can provide is not meant to be a movable/scalable/changable shape, it's meant for background text as shown on the original terrylinla sketch-canvas readme.

**Comment by QuevedoIB** [comment]
You're right I kept touching things after the PR to suit what I needed. I'm closing this.

**Comment by creambyemute** [comment]
@QuevedoIB Is the CDU change the only thing needed to fix the actual bug you encountered?
I'm not using the text array objects at all, so maybe you can shed a bit light onto it.

If it's just that I'll create a fix.

**Comment by QuevedoIB** [comment]
Removing the CDU was the only thing needed to fix it.

As ImageEditor is expecting:

```
text: PropTypes.arrayOf(
            PropTypes.shape({
                text: PropTypes.string,
                font: PropTypes.string,
                fontSize: PropTypes.number,
                fontColor: PropTypes.string,
                overlay: PropTypes.oneOf(["TextOnSketch", "SketchOnText"]),
                anchor: PropTypes.shape({ x: PropTypes.number, y: PropTypes.number }),
                position: PropTypes.shape({ x: PropTypes.number, y: PropTypes.number }),
                coordinate: PropTypes.oneOf(["Absolute", "Ratio"]),
                alignment: PropTypes.oneOf(["Left", "Center", "Right"]),
                lineHeightMultiple: PropTypes.number
            })
        )
```

The if statement causes conflict and creates an infinite loop of setSatets.

```
componentDidUpdate(prevProps, prevState) {
        if (prevState.text !== this.state.text) {
            this.setState({
                text: this.state.text
            });
        }
    }
```
I'm not using the text property anymore but I'd suggest to keep the lifecycle in case that text changes and a rerender is needed and simply fix the if statement to check if theres a text property and if so compare the texts from each object to see if they changed.

Or just remove the lifecycle, worst thing that could happen is that if text changes it won't rerender and change the displayed text.

**Pull request closed without merging**
